#!/usr/bin/env python3
"""Track whether a topic file is still the one the pipeline generated.

    manifest.py check <topic>     -> prints a status word, exit 0
    manifest.py stamp <topic>     -> records the file as pipeline-generated
    manifest.py ingested <topic>  -> records that the analyst absorbed this content

Statuses:
  absent      no <topic>/<topic>.md yet — nothing to preserve
  virgin      file exists but the pipeline has never seen it. Its content predates
              the forge and MUST be ingested before any write.
  ingested    not generated by us, but the analyst has absorbed this exact content
              into commands.yml — safe to regenerate, nothing will be lost
  unmodified  matches what we last generated — safe to regenerate wholesale
  modified    changed since we generated or ingested it — ingest again first

The manifest lives beside the dumps in _sources/<topic>/ (gitignored), so a
fresh clone reads 'virgin' and errs toward preserving content rather than
destroying it.

The repo, its layout and its sources directory all come from
.cheatsheet-repo.yml via forgeconfig, so the plugin does NOT have to live
inside the repo it operates on and makes no assumption about how topic files
are named. Run /cheatsheet-forge:init first.
"""
import hashlib
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import forgeconfig as fc          # noqa: E402


def paths(cfg, topic):
    return cfg.topic_md(topic), cfg.manifest(topic)


def digest(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()


def check(cfg, topic):
    md, man = paths(cfg, topic)
    if not md.exists():
        return "absent"
    if not man.exists():
        return "virgin"
    try:
        rec = json.loads(man.read_text())
    except Exception:
        return "virgin"
    if rec.get("sha256") != digest(md):
        return "modified"
    return "ingested" if rec.get("state") == "ingested" else "unmodified"


def record(cfg, topic, state):
    md, man = paths(cfg, topic)
    if not md.exists():
        print(f"cannot record: {md} does not exist")
        return 1
    man.parent.mkdir(parents=True, exist_ok=True)
    man.write_text(json.dumps({"topic": topic, "file": cfg.topic_md_rel(topic),
                               "state": state, "sha256": digest(md)}, indent=2) + "\n")
    print(f"{topic}: recorded as {state} ({digest(md)[:16]}...)")
    return 0


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(2)
    cfg = fc.require()
    action, topic = sys.argv[1], cfg.canonical(sys.argv[2])
    if action == "check":
        print(check(cfg, topic)); sys.exit(0)
    if action == "stamp":
        sys.exit(record(cfg, topic, "generated"))
    if action == "ingested":
        sys.exit(record(cfg, topic, "ingested"))
    print(f"unknown action: {action}"); sys.exit(2)
